[package]
name = "rget"
description = "Rust wget clone"
version = "0.1.0"
authors = ["John Doneth <doneth7@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.0-alpha.1"
indicatif = "0.12.0"
tokio = "0.2.0-alpha.6"
